/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AeRouteImport } from './routes/ae'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as StudyStudyIdRouteImport } from './routes/study.$studyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AeRoute = AeRouteImport.update({
  id: '/ae',
  path: '/ae',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyStudyIdRoute = StudyStudyIdRouteImport.update({
  id: '/study/$studyId',
  path: '/study/$studyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ae': typeof AeRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/sign-up': typeof SignUpRoute
  '/study/$studyId': typeof StudyStudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ae': typeof AeRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/sign-up': typeof SignUpRoute
  '/study/$studyId': typeof StudyStudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ae': typeof AeRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/sign-up': typeof SignUpRoute
  '/study/$studyId': typeof StudyStudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ae'
    | '/alerts'
    | '/audit'
    | '/login'
    | '/portfolio'
    | '/sign-up'
    | '/study/$studyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ae'
    | '/alerts'
    | '/audit'
    | '/login'
    | '/portfolio'
    | '/sign-up'
    | '/study/$studyId'
  id:
    | '__root__'
    | '/'
    | '/ae'
    | '/alerts'
    | '/audit'
    | '/login'
    | '/portfolio'
    | '/sign-up'
    | '/study/$studyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AeRoute: typeof AeRoute
  AlertsRoute: typeof AlertsRoute
  AuditRoute: typeof AuditRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  SignUpRoute: typeof SignUpRoute
  StudyStudyIdRoute: typeof StudyStudyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ae': {
      id: '/ae'
      path: '/ae'
      fullPath: '/ae'
      preLoaderRoute: typeof AeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$studyId': {
      id: '/study/$studyId'
      path: '/study/$studyId'
      fullPath: '/study/$studyId'
      preLoaderRoute: typeof StudyStudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AeRoute: AeRoute,
  AlertsRoute: AlertsRoute,
  AuditRoute: AuditRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  SignUpRoute: SignUpRoute,
  StudyStudyIdRoute: StudyStudyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
